# Use node_modules directory structure
nodeLinker: node-modules

# Enable TypeScript support
enableTelemetry: false

# Workspace settings
workspaces-experimental: true

# Package settings
enableGlobalCache: true

# Development settings
preferInteractive: true